### ISSUE TITLE
Failure Fetching Query Results

### ISSUE THREAD

**Issue by keith-nascent** [paradigmxyz/spice#5]
Running on Python 3.12.6

```
import spice
data = spice.query("123456", api_key=api_key, cache=False)
````

Getting the following error:

```
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/spice/test_spice_dune_analytics.py", line 13, in <module>
    data = spice.query("4314249", api_key=api_key, cache=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/spice/_extract.py", line 241, in query
    df = _get_results(**execute_kwargs, **result_kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/spice/_extract.py", line 869, in _get_results
    print(f"Response As JSON: {response.json()}")
                               ^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Fixed this by importing `simplejson` and adding it to the custom exceptions list of error handling.

**Comment by sslivkoff** [comment]
fixed in #6
